### ISSUE TITLE
Keep getting TOKEN_FETCH_ERROR, where do I put the .p8?

### ISSUE THREAD

**Issue by marc-lassiter** [assembleinc/kids-tunes-android#1]
I keep getting TOKEN_FETCH_ERROR:
TOKEN_FETCH_ERROR
public static final TokenError TOKEN_FETCH_ERROR
indicates error in fetching music token, say due to developer token invalid/exipred.

I have the token.xml changed but have no idea where to put the p8 key.

**Comment by harsh1711** [comment]
Hi, @marc-lassiter I am trying to integrate apple music into my android application. I am also facing a similar issue and unable to find any solution. If you found a solution for this could you please help me to resolve this error?

**Comment by ryanrahmans26** [comment]
> Hi, @marc-lassiter I am trying to integrate apple music into my android application. I am also facing a similar issue and unable to find any solution. If you found a solution for this could you please help me to resolve this error?

I hope this help

Install https://www.npmjs.com/package/apple-music-token-node
Use cli mode
input the apple team id
input the music key id
drag the .p8 to the terminal

Then copas the ouput developer token to tokens.xml (or create tokens.xml first)

This app is working 100%.
